name: Say Hello

on:
  push:
    branches:
      - main
      - list-starships

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Alex!"
      - name: Echo the message
        run: |
          echo "Que tal?"

